name: SimpleStack
version: ${project.version}
main: com.mikedeejay2.simplestack.SimpleStack
api-version: 1.13
authors:
  - Mikedeejay2

commands:
  simplestack:
    description: Simple Stack base command.
    aliases:
      - ss
      - stack
      - sstack

permissions:
  simplestack.use:
    description: Allow a player to stack normally unstackable items to 64
    default: true
  simplestack.reload:
    description: Allow a player to reload the simplestack config
  simplestack.help:
    description: Allow a player to access the help command help screen (admin commands)
  simplestack.reset:
    description: Allow a player to reset the simplestack config to default values
  simplestack.setamount:
    description: Allow a player to set the item currently held in their hand to any amount
  simplestack.additem:
    description: Allow a player to add a unique item to the unique items list
  simplestack.removeitem:
    description: Allow a player to remove a unique item from the unique items list
  simplestack.config:
    description: Allow a player to open and modify the configuration from a GUI